void gematrias(char *word, char *text);
int checkWordGeo(char *word);
void checkFromGeo(char *text, int needSum,int* flag);
void anagram(char *word, char *text);
int fullArrAndlength(char *word,int chars[]);
void myCopyArr(int src[],int dest[]);
void checkFromAnag(char *text, int coChars[], int length,int *flag);
void atbash(char* word, char* text);
void atbashWord(char* word, char* atbash);
void reverseAtbash(char* atb, char* reverseAt);
int arraySize(char* arr);
void checkNprint(char* text, char* word, int size, int* flag);